### ISSUE TITLE
build main.c failed

### ISSUE THREAD

**Issue by viperfx** [jianglei12138/python3#2]
I have tried to follow the instructions to see if I can compile my own libmain.so file however I get the following error when compiling

```
In file included from main.c:1:0:
main.h:2:17: fatal error: jni.h: No such file or directory
 #include <jni.h>
                 ^
compilation terminated.
```

**Comment by jianglei12138** [comment]
You must use arm-linux-androideabi which exported by NDK. 

#### 1.make cross compile toolchain

In termial, just cd your NDK path (must in this folder) and input

``` shell
./build/tools/make-standalone-toolchain.sh --arch=arm --platform=android-17
```

like this 

![er](https://github.com/jianglei12138/cups/raw/master/art/toolchain.png)

#### 2.environment variables

You can edit you profile file or just input this in termial: 

``` shell
export PATH=${PATH}:/path/to/your/arm-linux-androideabi-4.8/bin
```

#### 3.compile

Before compilation, copy the dependent dynamic library and static library `python3.5m` `locale` `readline` `history` `termcap` and these shared library and sourde code could be found on

```
https://github.com/jianglei12138/readline 
```

and 

```
https://github.com/jianglei12138/liblocale
```

libpython3.5m.a was compile by python3

Then put these library to your toolchain /sysroot/usr/lib/ (Just for convenience).

Compile

``` shell
arm-linux-androideabi-gcc main.c -o libmain.so -lpython3.5m -lz -lm -llocale -lreadline -lhistory -ltermcap -fPIE -pie -shared -llog
```

#### 4.Done

DO NOT USE STRIP COMMAND.

**Comment by viperfx** [comment]
Thanks very much for the instructions! One last help, could you provide a pre-built libpython3.5m.a?

**Comment by jianglei12138** [comment]
You can find it in [system.tar.gz](https://github.com/jianglei12138/python3/blob/master/system.tar.gz)

**Comment by viperfx** [comment]
Great, thanks! It seems to work. I compiled my new main.m (I changed a small log statement and it seems to be reflecting the changes).

I still get an error, which I have reported in the other issue. 

```
04-23 22:35:21.453 12634-12634/com.example.pythontest I/JNIEnv: import python module failed!!
```

Thanks for all the help so far!
