### ISSUE TITLE
Launching python from shell

### ISSUE THREAD

**Issue by viperfx** [jianglei12138/python3#3]
I think the instructions are missing a few steps perhaps? I tried launching python through the adb shell and I got the following issue.

```
root@hammerhead:/ # export PYTHONPATH=$PYTHONPATH:/sdcard/python35.zip
root@hammerhead:/ # python
sush: python: not found
```

**Comment by jianglei12138** [comment]
Of course, you should push the executable binary to your device (/system/bin/) and push the python35.zip to sdcard.

**Comment by viperfx** [comment]
Ah yea, I figured that might be the case. I was trying to look for the executable in the project. Hmm I feel like there was a system.tar.gz with a python executable in it? Do I need to compile it?

I would like to help you with some documentation. I think I can add many of the little steps in between that you take for granted :)

**Comment by jianglei12138** [comment]
Thank you, I think I'm not good at writing document, especially in english.  Could you help me??

**Comment by viperfx** [comment]
Yes, ofcourse. No problem. I think personally writing the documentation is a good way to learn all this new stuff for me. Let me fork the project and add PR's as I learn new things. 

No actually your english is fine. I am able to understand most things you say without any issue. I think the fallacy is that smart people like you assume many things that is common knowledge. I can help you with that and make it a bit more approachable for everyone else. 

So lets start with this python executable. Is that in the repo? Are the steps in the readme about compilation the steps to follow to get the executable?

**Comment by jianglei12138** [comment]
Of course you can get the executable in the repo.  [Here](https://github.com/jianglei12138/python3/blob/a86034a01f5f39f6dbe80be517fc1895dc1e47f9/system.tar.gz).

And I remove it because it cannot execute on android 4.4

**Comment by viperfx** [comment]
Ok. 

So I have done the following:
- Use rooted file manager to move python3 executable to /system/bin
- Set python path to /sdcard/python3.5.zip

When running python3 in the adb shell I get the following error

```
root@hammerhead:/ # python3
CANNOT LINK EXECUTABLE: library "liblocale.so" not found
```

I moved the files inside armeabi-v7a to /system/lib so that fixed the issue. 

But now it says ... and I don't have this file.

```
CANNOT LINK EXECUTABLE: library "libreadline.so" not found
```

**Comment by jianglei12138** [comment]
Readline could be found [here](https://github.com/jianglei12138/readline).  You can disable readline when compile in file Modules/Setup.

**Comment by viperfx** [comment]
Ah okay! Okay so I have a python shell in adb running now! There are a couple of warning but it seems okay so far:

```
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Python 3.5.1 (default, Apr 12 2016, 14:09:29)
[GCC 4.6 20120106 (prerelease)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

So I added a python library inside the python3.5 folder and zipped it up and used that as the PYTHONPATH, I tried launching python3 after that and it crashes.

```
root@hammerhead:/ # python3
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: can't initialize sys standard streams
ImportError: No module named 'encodings'

Current thread 0xb6d3db34 (most recent call first):
Aborted
```

**Comment by jianglei12138** [comment]
I don't know why this was happened, I will test it. And After fix the crash, I have changed the structure of jni. So it doesn't need to use arm-linux-androideabi-gcc to compile. You can directly use `ndk-build` command. Sorry for I didn't say that. I made some changes to your README.

**Comment by viperfx** [comment]
Oh okay. I ran ndk-build and it crashed at first. I had to change the platform to `android-23` in Application.mk and it created the shared libraries correctly. So this is just to compile the main.c fie right? This does not related to the issue with python shell in adb?
Also what is the purpose of libpython3.5.so?

**Comment by jianglei12138** [comment]
Yes, it doesn't related to the issue with python shell in adb. And you can use it directly without compile the repo. What you need is the python3.5.zip (library of python)  and the jni.

**Comment by jianglei12138** [comment]
Adb shell is just to test if the library could work successfully.

**Comment by viperfx** [comment]
Yep, that makes sense. I had assumed that too. Adb shell would be really useful to have working.
